# Generated by Django 4.2.5 on 2023-10-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("feedback", models.TextField()),
                ("img_url", models.URLField()),
            ],
        ),
    ]
