# Generated by Django 4.2.5 on 2023-10-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="img_url",
            field=models.ImageField(
                blank=True, default="skills/inledrobot.jpg", null=True, upload_to=""
            ),
        ),
    ]
